// @ts-check
import { test, expect } from '@playwright/test';
import fs from 'fs';
import path from 'path';

// Read test URLs from the file generated by global setup
const testDataPath = path.join(process.cwd(), 'tests', 'test-urls.json');
/** @type {{ hrefs: string[] }} */
let testData = { hrefs: [] };

try {
    const fileContent = fs.readFileSync(testDataPath, 'utf-8');
    testData = JSON.parse(fileContent);
} catch (error) {
    console.error('Failed to read test URLs from global setup:', error);
}

/** @type {string[]} */
const hrefs = testData.hrefs;

// Shared context and page for all tests to maintain IndexedDB state
/** @type {import('@playwright/test').BrowserContext} */
let context;

// Generate a timestamped results filename for this run (DD-MM-YY-HH-MM)
function makeResultsPath() {
    const now = new Date();
    const dd = String(now.getDate()).padStart(2, '0');
    const mm = String(now.getMonth() + 1).padStart(2, '0');
    const yy = String(now.getFullYear()).slice(-2);
    const hh = String(now.getHours()).padStart(2, '0');
    const min = String(now.getMinutes()).padStart(2, '0');
    return path.join(process.cwd(), 'tests', `test-results-${dd}-${mm}-${yy}-${hh}-${min}.json`);
}

// Fixed at module load time so all saves during this run go to the same file
const resultsPath = makeResultsPath();

// Configure tests to run serially and share browser context for IndexedDB persistence
test.describe.configure({ mode: 'serial' });

test.describe('Test each chart library', () => {
    test.beforeAll(async ({ browser }) => {
        console.warn('beforeAll');
        // Each run starts fresh — results are written to a new timestamped file
        console.log('Results for this run will be saved to:', resultsPath);
        context = await browser.newContext();
    });

    test.afterEach(async () => {
        // Save results incrementally after each test so partial results are not lost on failure
        if (context) {
            try {
                await context.storageState({ path: resultsPath, indexedDB: true });
                console.log('Results saved after test');
            } catch (error) {
                console.warn('Failed to save results after test:', error.message);
            }
        }
    });

    test.afterAll(async () => {
        // Final save then close context
        if (context) {
            try {
                console.log('Saving final results to:', resultsPath);
                await context.storageState({ path: resultsPath, indexedDB: true });
            } catch (error) {
                console.warn('Failed to save final results:', error.message);
            }
            try {
                await context.close();
            } catch (error) {
                console.warn('Failed to close context:', error.message);
            }
        }
    });

    for (const href of hrefs) {
        // Generate test name from URL - trim first segment
        const urlParts = href.split('/').filter((part) => part.length > 0);
        const testName = urlParts.slice(1).join('/') || href;

        test(testName, async () => {
            test.setTimeout(300000);

            console.log(`Test: ${testName} - ${href}`);
            const page = await context.newPage();

            page.on('crash', () => {
                console.error(`Page crashed during test: ${testName}`);
            });

            try {
                await page.goto(`http://localhost:5173/${href}`);
                await page.waitForSelector('.results-table-ready', { timeout: 600000 });

                // Generate PDF filename from URL - sanitize the href for filename
                const pdfFilename = href.replace(/[^a-zA-Z0-9]/g, '-') + '.pdf';
                await page.pdf({ path: pdfFilename, format: 'A4' });
            } finally {
                await page.close().catch((e) => console.warn('Error closing page:', e.message));
            }
        });
    }

    test('Results Summary', async () => {
        console.log('refresh summary');
        const page = await context.newPage();
        try {
            await page.goto('http://localhost:5173/');
            await page.waitForSelector('.results-ready');

            // Save the initial page as PDF
            await page.pdf({ path: 'results-summary-page.pdf', format: 'A4' });
        } finally {
            await page.close().catch((e) => console.warn('Error closing page:', e.message));
        }
    });
});
