// @ts-check
import { test } from '@playwright/test';
import fs from 'fs';
import path from 'path';

// Read test URLs from the file generated by global setup
const testDataPath = path.join(process.cwd(), 'tests', 'test-urls.json');
/** @type {{ hrefs: string[] }} */
let testData = { hrefs: [] };

try {
    const fileContent = fs.readFileSync(testDataPath, 'utf-8');
    testData = JSON.parse(fileContent);
} catch (error) {
    console.error('Failed to read test URLs from global setup:', error);
}

/** @type {string[]} */
const hrefs = testData.hrefs;

// Generate a timestamped results filename for this run (DD-MM-YY-HH-MM)
function makeResultsPath() {
    const now = new Date();
    const dd = String(now.getDate()).padStart(2, '0');
    const mm = String(now.getMonth() + 1).padStart(2, '0');
    const yy = String(now.getFullYear()).slice(-2);
    const hh = String(now.getHours()).padStart(2, '0');
    const min = String(now.getMinutes()).padStart(2, '0');
    return path.join(process.cwd(), 'tests', `test-results-${dd}-${mm}-${yy}-${hh}-${min}.json`);
}

// Fixed at module load time so all saves during this run go to the same file
const resultsPath = makeResultsPath();

// Group hrefs by library (first URL path segment, e.g. 'scichart', 'echarts')
/** @type {Map<string, string[]>} */
const libraryGroups = new Map();
for (const href of hrefs) {
    const lib = href.split('/').filter(Boolean)[0] ?? 'unknown';
    if (!libraryGroups.has(lib)) libraryGroups.set(lib, []);
    libraryGroups.get(lib).push(href);
}

console.log(`Results for this run will be saved to: ${resultsPath}`);
console.log(`Found ${libraryGroups.size} libraries: ${[...libraryGroups.keys()].join(', ')}`);

// ── Per-library describe blocks ────────────────────────────────────────────
// Each library gets its own browser context. afterAll closes the context which
// terminates the renderer process and deterministically reclaims WebGL / GPU memory
// before the next library starts.

for (const [lib, libHrefs] of libraryGroups) {
    test.describe(lib, () => {
        /** @type {import('@playwright/test').BrowserContext} */
        let context;

        test.beforeAll(async ({ browser }) => {
            console.log(`[${lib}] Creating browser context (${libHrefs.length} tests)`);
            // Load accumulated results from earlier libraries in this run
            const contextOptions = fs.existsSync(resultsPath)
                ? { storageState: resultsPath }
                : {};
            context = await browser.newContext(contextOptions);
        });

        test.afterEach(async () => {
            // Incremental save — preserves results even if a later test crashes the page
            if (context) {
                try {
                    await context.storageState({ path: resultsPath, indexedDB: true });
                } catch (error) {
                    console.warn(`[${lib}] Failed to save results after test:`, error.message);
                }
            }
        });

        test.afterAll(async () => {
            if (context) {
                // Save first, then destroy — context.close() wipes IndexedDB from memory
                try {
                    await context.storageState({ path: resultsPath, indexedDB: true });
                    console.log(`[${lib}] Results saved`);
                } catch (error) {
                    console.warn(`[${lib}] Failed to save final results:`, error.message);
                }
                try {
                    await context.close();
                    console.log(`[${lib}] Context closed — GPU resources reclaimed`);
                } catch (error) {
                    console.warn(`[${lib}] Failed to close context:`, error.message);
                }
                context = undefined;

                // Brief pause to allow GPU resources to be garbage-collected
                // before the next library's browser context is created
                console.log(`[${lib}] Waiting 3s for GPU cleanup...`);
                await new Promise(resolve => setTimeout(resolve, 3000));
            }
        });

        for (const href of libHrefs) {
            const urlParts = href.split('/').filter((part) => part.length > 0);
            const testName = urlParts.slice(1).join('/') || href;

            test(testName, async () => {
                test.setTimeout(300000);

                console.log(`[${lib}] ${testName}`);
                const page = await context.newPage();

                page.on('crash', () => {
                    console.error(`[${lib}] Page crashed: ${testName}`);
                });

                try {
                    await page.goto(`http://localhost:5173/${href}`);
                    await page.waitForSelector('.results-table-ready', { timeout: 600000 });

                    const pdfFilename = href.replace(/[^a-zA-Z0-9]/g, '-') + '.pdf';
                    await page.pdf({ path: pdfFilename, format: 'A4' });
                } finally {
                    await page.close().catch((e) => console.warn(`[${lib}] Error closing page:`, e.message));
                }
            });
        }
    });
}

// ── Results Summary ────────────────────────────────────────────────────────
// Runs in its own fresh context after all library tests complete

test.describe('Results Summary', () => {
    test('summary', async ({ browser }) => {
        const contextOptions = fs.existsSync(resultsPath)
            ? { storageState: resultsPath }
            : {};
        const ctx = await browser.newContext(contextOptions);
        const page = await ctx.newPage();
        try {
            console.log('Loading results summary page');
            await page.goto('http://localhost:5173/');
            await page.waitForSelector('.results-ready');
            await page.pdf({ path: 'results-summary-page.pdf', format: 'A4' });
        } finally {
            await page.close().catch(() => {});
            await ctx.close().catch(() => {});
        }
    });
});
